name: This is a contexts testing github actions pipeline

on: 
   push:
     branches: [main]

jobs:
   contexts_build:
   runs-on: ubuntu-latest
   steps:

     - name: checkout source 
       uses: actions/checkout@v4

       
     - name: context testing
       run: echo "Repo: ${{ github.repository }}, Branch: ${{ github.ref }}" 