name: github actions contexts testing

on:
  push:
    branches: [ main ]

jobs:
  context_build:
    env: 
      MY_ENV: "test"
    runs-on: ubuntu-latest
    steps:
      - name: contexts build to check the values in github actions
        uses: actions/checkout@v4

      - name: context build from github actions
        run: |
          echo "Repo: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "commit: ${{ github.sha }}"
          echo "Events: ${{ github.event_name }}"
          echo "Actors: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run number: ${{ github.run_number }}"
          echo "Job: ${{ github.job }}"
          echo "Github token: ${{ github.token }}"
          echo "Github workspace: ${{ github.workspace }}"
          echo "Env: ${{ github.env }}"
          echo "Runner: ${{ runner.os }}"


      - name: notify if context failure
        if: failure()
        run: echo "Build context info pipeline failure"

      - name: notify if pipeline success
        if: success()
        run: echo "Build pipeline is successfully executed"

      - name: deep cleanup after pipeline completion
        if: always()
        run: |
         rm -rf ${{github.workspace }}/*
         echo "Workspace: ${{ github.workspace }} is cleaned"
