name: github actions contexts testing

on:
  push:
    branches: [ main ]

jobs:
  context_build:
    runs-on: ubuntu-latest
    steps:
      - name: contexts build to check the values in github actions
        uses: actions/checkout@v4

      - name: context build from github actions
        run: |
          echo "Repo: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "commit: ${{ github.sha }}"
          echo "Events: ${{ github.event_name }}"
          echo "Actors: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run number: ${{ github.run_number }}"
          echo "Job: ${{ github.job }}"