name: manually rtiggering this workflow 

on:
    workflow_dispatch:


jobs:
    Build_job:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v4

            - name: build code
              run: echo "Hello world"